"""All tool modules, in the order they get registered on the MCP server."""

from . import (
    account_access,
    accounts,
    ad_groups,
    ads,
    assets,
    audiences,
    bidding,
    billing,
    budgets,
    bulk,
    campaign_types,
    campaigns,
    conversions,
    experiments,
    keyword_planner,
    keywords,
    labels,
    performance_max,
    recommendations,
    reporting,
    shared_sets,
    targeting,
)

ALL_MODULES = [
    accounts,
    account_access,
    reporting,
    billing,
    campaigns,
    campaign_types,
    budgets,
    bidding,
    targeting,
    ad_groups,
    ads,
    assets,
    labels,
    keywords,
    shared_sets,
    keyword_planner,
    bulk,
    audiences,
    conversions,
    experiments,
    performance_max,
    recommendations,
]
