"""All tool modules, in the order they get registered on the MCP server."""

from . import (
    accounts,
    ad_groups,
    ads,
    assets,
    audiences,
    bidding,
    budgets,
    bulk,
    campaign_types,
    campaigns,
    conversions,
    keyword_planner,
    keywords,
    performance_max,
    recommendations,
    reporting,
    targeting,
)

ALL_MODULES = [
    accounts,
    reporting,
    campaigns,
    campaign_types,
    budgets,
    bidding,
    targeting,
    ad_groups,
    ads,
    assets,
    keywords,
    keyword_planner,
    bulk,
    audiences,
    conversions,
    performance_max,
    recommendations,
]
