"""Google Ads recommendation tools: read, apply, and dismiss them.

Recommendations are account-level optimization suggestions generated by
Google (e.g. add keywords, enable sitelinks, fix ad strength, adjust bids).
Applying or dismissing a recommendation is a write operation and therefore
goes through the safety propose/confirm layer.
"""

from __future__ import annotations

from ..context import AppContext
from ..errors import GoogleAdsMcpError, format_google_ads_exception
from ..helpers import normalize_customer_id


def register(mcp, ctx: AppContext) -> None:
    @mcp.tool()
    def get_recommendations(customer_id: str, type_filter: str | None = None) -> dict:
        """List active Google Ads recommendations for the account.

        Args:
            type_filter: Optional recommendation type, e.g. "KEYWORD",
                "SITELINK_ASSET", "RESPONSIVE_SEARCH_AD", "TARGET_ROAS_OPT_IN".
                See Google Ads API docs for the full enum.
        """
        where_parts = ["recommendation.status = 'UNCLASSIFIED'"]
        if type_filter:
            where_parts.append(f"recommendation.type = '{type_filter.upper()}'")

        query = f"""
            SELECT
                recommendation.resource_name,
                recommendation.type,
                recommendation.impact.base_metrics.clicks,
                recommendation.impact.base_metrics.cost_micros,
                recommendation.impact.base_metrics.conversions,
                recommendation.impact.base_metrics.impressions,
                recommendation.campaign,
                recommendation.ad_group
            FROM recommendation
            WHERE {" AND ".join(where_parts)}
            ORDER BY recommendation.impact.base_metrics.cost_micros DESC
            LIMIT 500
        """
        rows = ctx.client.search(customer_id, query)
        return {"recommendations": rows, "count": len(rows)}

    @mcp.tool()
    def apply_recommendation(customer_id: str, resource_name: str) -> dict:
        """Propose applying a Google Ads recommendation by resource_name.

        The change is staged; call confirm_pending_action(action_id) to
        actually execute it.
        """
        from google.ads.googleads.errors import GoogleAdsException

        customer_id_norm = normalize_customer_id(customer_id)

        def execute():
            client = ctx.client.raw
            service = client.get_service("RecommendationService")
            operation = client.get_type("ApplyRecommendationOperation")
            operation.resource_name = resource_name

            try:
                result = service.apply_recommendation(
                    customer_id=customer_id_norm, operations=[operation]
                )
            except GoogleAdsException as ex:
                raise GoogleAdsMcpError(format_google_ads_exception(ex)) from ex

            return result

        return ctx.safety.propose(
            tool_name="apply_recommendation",
            customer_id=customer_id,
            description=f"Apply recommendation {resource_name}",
            payload={"resource_name": resource_name},
            execute=execute,
        )

    @mcp.tool()
    def dismiss_recommendation(customer_id: str, resource_name: str) -> dict:
        """Propose dismissing a Google Ads recommendation by resource_name.

        Dismissing stops Google from showing the suggestion again in the UI.
        Like apply_recommendation, this is staged until confirmed.
        """
        from google.ads.googleads.errors import GoogleAdsException

        customer_id_norm = normalize_customer_id(customer_id)

        def execute():
            client = ctx.client.raw
            service = client.get_service("RecommendationService")
            operation = client.get_type("DismissRecommendationOperation")
            operation.resource_name = resource_name

            try:
                result = service.dismiss_recommendation(
                    customer_id=customer_id_norm, operations=[operation]
                )
            except GoogleAdsException as ex:
                raise GoogleAdsMcpError(format_google_ads_exception(ex)) from ex

            return result

        return ctx.safety.propose(
            tool_name="dismiss_recommendation",
            customer_id=customer_id,
            description=f"Dismiss recommendation {resource_name}",
            payload={"resource_name": resource_name},
            execute=execute,
        )
